package org.netbeans.rest.application.config;

import jakarta.ws.rs.core.Application;

@jakarta.ws.rs.ApplicationPath("api")
public class ApplicationConfig extends Application {

//    @Override
//    public Set<Class<?>> getClasses() {
//        return getRestResourceClasses();
//    }
//
//    /**
//     * Do not modify this method. It is automatically generated by NetBeans REST support.
//     */
//    private Set<Class<?>> getRestResourceClasses() {
//        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
//        resources.add(lanstar.memberportal.controller.MPAccessCtrl.class);
//        resources.add(lanstar.memberportal.controller.MPLoanCtrl.class);
//        resources.add(lanstar.memberportal.controller.MPMemberCtrl.class);
//        resources.add(lanstar.memberportal.controller.MPExpayCtrl.class);
//        resources.add(lanstar.memberportal.controller.MPReportsCtrl.class);
//        resources.add(lanstar.memberportal.controller.MPMemberUpdatesCtrl.class);
//        return resources;
//    }

}
